// #################   LOCAL HOST  #####################
//GET ALL PROPERTIES
GET http://localhost:5000/properties
###
// GET ALL TENANTS
GET http://localhost:5000/tenants
###
// GET PROPERTY BY ID
GET http://localhost:5000/properties/646687744676e7468f8b1a4b
###
// GET TENANT BY ID
GET http://localhost:5000/tenants/646688844676e7468f8b1a4d
###

// LOCAL HOST - CREATE NEW PROPERTY
###
POST http://localhost:5000/properties HTTP/1.1
Content-type: application/json

{
    "propertyName":"TEST", 
    "address":"123 somewhere street"
}

// LOCAL HOST - CREATE NEW TENANT
###
POST http://localhost:5000/tenants HTTP/1.1
Content-type: application/json

{
    "firstName":"Paige", 
    "lastName":"Brady", 
    "email":"paige@fakeemail.com", 
    "propertyAddr":"pink", 
    "monthlyRent":"1000",
    "leaseStart":"03/11/15",
    "leaseEnd":"5/31/33"
}

// LOCAL HOST - UPDATE PROPERTY
###
PUT http://localhost:5000/properties/ID HTTP/1.1
Content-type: application/json

{
    "propertyName":"UPDATE TEST", 
    "address":"456 future place"
}

// LOCAL HOST - UPDATE TENANT
###
PUT http://localhost:5000/tenants/ID HTTP/1.1
Content-type: application/json

{
    "firstName":"Brooke", 
    "lastName":"Brady", 
    "email":"brooke@fakeemail.com", 
    "propertyAddr":"purple", 
    "monthlyRent":"1000",
    "leaseStart":"05/02/13",
    "leaseEnd":"5/31/31"
}

// LOCAL HOST - DELETE PROPERTY
###
DELETE http://localhost:5000/properties/ID HTTP/1.1

// LOCAL HOST - DELETE TENANT
###
DELETE http://localhost:5000/tenants/ID HTTP/1.1
###


// #################   PRODUCTION DEPLOY - RENDER  #####################


// RENDER - GET ALL PROPERTIES
GET https://cse341-realestateapi.onrender.com/properties
###
// RENDER - GET PROPERTY BY ID
GET https://cse341-realestateapi.onrender.com/properties/ID
###
// RENDER - GET ALL TENANTS
GET https://cse341-realestateapi.onrender.com/tenants
###
// RENDER - GET TENANT BY ID
GET https://cse341-realestateapi.onrender.com/tenants/ID
###


// RENDER - CREATE NEW PROPERTY
###
POST https://cse341-realestateapi.onrender.com/properties HTTP/1.1
Content-type: application/json

{
    "propertyName":"CREATE NEW PROPERTY", 
    "address":"987 ABC road"
}

// RENDER - CREATE NEW TENANT
###
POST https://cse341-realestateapi.onrender.com/tenants HTTP/1.1
Content-type: application/json

{
    "firstName":"NEW", 
    "lastName":"TENANT", 
    "email":"TEST@fakeemail.com", 
    "propertyAddr":"purple", 
    "monthlyRent":"5000",
    "leaseStart":"05/01/23",
    "leaseEnd":"5/31/24"
}

// RENDER - UPDATE PROPERTY
###
PUT https://cse341-realestateapi.onrender.com/properties/6455a907ea3259b5cd9f585a HTTP/1.1
Content-type: application/json

{
    "propertyName":"UPDATED PROPERTY", 
    "address":"111 Updated Rd"
}

// RENDER - UPDATE TENANT
###
PUT https://cse341-realestateapi.onrender.com/tenants/6455a907ea3259b5cd9f585a HTTP/1.1
Content-type: application/json

{
    "firstName":"UPDATED", 
    "lastName":"TENANT", 
    "email":"UPDATED@fakeemail.com", 
    "propertyAddr":"purple", 
    "monthlyRent":"5000",
    "leaseStart":"05/01/23",
    "leaseEnd":"5/31/24"
}

// RENDER - DELETE PROPERTY
###
DELETE https://cse341-realestateapi.onrender.com/properties/6455a907ea3259b5cd9f585a HTTP/1.1

// RENDER - DELETE TENANT
###
DELETE https://cse341-realestateapi.onrender.com/tenants/6455a907ea3259b5cd9f585a HTTP/1.1