// #################   LOCAL HOST  #####################
### GET ALL PROPERTIES
GET http://localhost:8080/properties

### GET ALL TENANTS
GET http://localhost:8080/tenants

### GET PROPERTY BY ID
GET http://localhost:8080/properties/646687744676e7468f8b1a4b

### GET TENANT BY ID
GET http://localhost:8080/tenants/646688844676e7468f8b1a4d


###  CREATE NEW PROPERTY
POST http://localhost:8080/properties HTTP/1.1
Content-type: application/json

{
    "propertyName":"TESTING 123", 
    "address":"123 somewhere street"
}

### CREATE NEW TENANT
POST http://localhost:8080/tenants HTTP/1.1
Content-type: application/json

{
    "firstName":"DEBUG", 
    "lastName":"Testing", 
    "email":"test@fakeemail.com", 
    "propertyAddr":"pink", 
    "monthlyRent":"1000",
    "leaseStart":"01/11/11",
    "leaseEnd":"01/31/33"
}

### UPDATE PROPERTY
PUT http://localhost:8080/properties/6466a73c279ea783bafd48f8 HTTP/1.1
Content-type: application/json

{
    "propertyName":"UPDATE TEST", 
    "address":"456 future place"
}


###  UPDATE TENANT
PUT http://localhost:8080/tenants/646fd482dd27a2ea42708536 HTTP/1.1
Content-type: application/json

{
    "firstName":"Brooke", 
    "lastName":"TEST", 
    "email":"debugging@fakeemail.com", 
    "propertyAddr":"purple", 
    "monthlyRent":"1000",
    "leaseStart":"05/02/13",
    "leaseEnd":"5/31/31"
}


### DELETE PROPERTY
DELETE http://localhost:8080/properties/ID HTTP/1.1


### DELETE TENANT
DELETE http://localhost:8080/tenants/646fd482dd27a2ea42708536 HTTP/1.1



// #################   PRODUCTION DEPLOY - RENDER  #####################

### GET ALL PROPERTIES
GET https://cse341-realestateapi.onrender.com/properties

###  GET PROPERTY BY ID
GET https://cse341-realestateapi.onrender.com/properties/ID

###  GET ALL TENANTS
GET https://cse341-realestateapi.onrender.com/tenants

### GET TENANT BY ID 
GET https://cse341-realestateapi.onrender.com/tenants/ID


### CREATE NEW PROPERTY
POST https://cse341-realestateapi.onrender.com/properties HTTP/1.1
Content-type: application/json

{
    "propertyName":"CREATE NEW PROPERTY", 
    "address":"987 ABC road"
}


### CREATE NEW TENANT
POST https://cse341-realestateapi.onrender.com/tenants HTTP/1.1
Content-type: application/json

{
    "firstName":"NEW", 
    "lastName":"TENANT", 
    "email":"TEST@fakeemail.com", 
    "propertyAddr":"purple", 
    "monthlyRent":"5000",
    "leaseStart":"05/01/23",
    "leaseEnd":"5/31/24"
}


### UPDATE PROPERTY
PUT https://cse341-realestateapi.onrender.com/properties/6455a907ea3259b5cd9f585a HTTP/1.1
Content-type: application/json

{
    "propertyName":"UPDATED PROPERTY", 
    "address":"111 Updated Rd"
}


### UPDATE TENANT
PUT https://cse341-realestateapi.onrender.com/tenants/6455a907ea3259b5cd9f585a HTTP/1.1
Content-type: application/json

{
    "firstName":"UPDATED", 
    "lastName":"TENANT", 
    "email":"UPDATED@fakeemail.com", 
    "propertyAddr":"purple", 
    "monthlyRent":"5000",
    "leaseStart":"05/01/23",
    "leaseEnd":"5/31/24"
}


### DELETE PROPERTY
DELETE https://cse341-realestateapi.onrender.com/properties/6455a907ea3259b5cd9f585a HTTP/1.1


### DELETE TENANT
DELETE https://cse341-realestateapi.onrender.com/tenants/6455a907ea3259b5cd9f585a HTTP/1.1